### ISSUE TITLE
There's no accent in "Edición" of the home screen

### ISSUE THREAD

**Issue by kAbAsTrEiT** [gb-mobile/pokecrystal-mobile-spa#8]
I have seen that in the tiles of the home screen the Spanish mobile rom there is no accent in "Edición". I send image of the original rom BYTS and BXTS to see the difference.

![IMG_20240919_202835](https://github.com/user-attachments/assets/505cf1d6-96a0-4dd0-8f56-aab3869b9136)
![IMG_20240919_202902](https://github.com/user-attachments/assets/ef2f16bb-87e6-4f03-a830-1176a13857ba)

**Comment by gb-mobile** [comment]
Fixed with https://github.com/gb-mobile/pokecrystal-mobile-spa/commit/7a3b09fe0c99a1b65661f17903cbd7ed9294d406
